#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 24 20:09:36 IST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim core_tb_behav -key {Behavioral:sim_1:Functional:core_tb} -tclbatch core_tb.tcl -log simulate.log"
xsim core_tb_behav -key {Behavioral:sim_1:Functional:core_tb} -tclbatch core_tb.tcl -log simulate.log

