# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rkvp/Desktop/DOP/core/core.srcs/sources_1/ip/dist_data_mem/dist_data_mem.xci
# IP: The module: 'dist_data_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rkvp/Desktop/DOP/core/core.gen/sources_1/ip/dist_data_mem/dist_data_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_data_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/rkvp/Desktop/DOP/core/core.srcs/sources_1/ip/dist_data_mem/dist_data_mem.xci
# IP: The module: 'dist_data_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rkvp/Desktop/DOP/core/core.gen/sources_1/ip/dist_data_mem/dist_data_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_data_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
